
# MNIST dataset config file

root: /home/nerf/datav/Dataset/MNIST/raw
train: 
  labels: train-labels-idx1-ubyte
  images: train-images-idx3-ubyte
test:
  labels: t10k-labels-idx1-ubyte
  images: t10k-images-idx3-ubyte
